### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by adelmemariani** [OpenEnergyPlatform/oekg-builder#3]
Hexagon nodes and Zoomable layout when clicking a node.

![Screenshot 2022-03-31 at 14 08 51](https://user-images.githubusercontent.com/7637364/161051763-49389b08-0c07-4be1-9428-5bc3e1f660b5.png)

![Screenshot 2022-03-31 at 14 09 16](https://user-images.githubusercontent.com/7637364/161051684-b2b87a8a-cb8f-4214-82c2-25986256e030.png)

**Comment by Ludee** [comment]
This looks super cool! Thanks for sharing.
I will try to test it next week!

**Comment by adelmemariani** [comment]
deprecated!
